### ISSUE TITLE
Who wants to take the project?

### ISSUE THREAD

**Issue by tboerger** [javierav/mongoid_userstamp#33]
Since I'm not using any mongodb anymore I would like to give this gem away. If @johnnyshields wants to take it I'm totally fine. Otherwise maybe somebody from the community wants to take the ownership?

**Comment by tboerger** [comment]
Ping @johnnyshields

**Comment by anilmaurya** [comment]
Hi @tboerger 

If @johnnyshields is not interested than I would like to maintain this project for `rails 5` and `mongoid 6` support.

**Comment by tboerger** [comment]
> If @johnnyshields is not interested than I would like to maintain this project for rails 5 and mongoid 6 support.

Since @johnnyshields doesn't respond so far I'm totally fine with that. I'm not using it anymore and I'm already involved in various other projects. So it makes sense to hand it over to somebody who got the time for that.

**Comment by javierav** [comment]
If @anilmaurya is not interested I would like to maintain this project for my organization. We still using MongoDB in our developments! 😉

**Comment by anilmaurya** [comment]
@javierav Please Go Ahead 👍. Currently I am not working on mongodb projects.

**Comment by tboerger** [comment]
@javierav I can transfer the project to you and add you as an admin to the rubygems project if you want. What's your rubygems.org email address?

**Comment by tboerger** [comment]
Are yopu also interested in https://github.com/tbpro/mongoid_find_by or https://github.com/tbpro/mongoid_toggle?

**Comment by javierav** [comment]
Hi @tboerger! My rubygems email address is the same that appear on my github profile page. For now I'm not interested in the other repositories, thanks 😉

**Comment by tboerger** [comment]
You just need to accept the transfer. Glad that this useful gem gets a new home.

**Comment by javierav** [comment]
@tboerger can you resend the transfer? I had the notification email wrongly configured 😖

**Comment by tboerger** [comment]
Resent the transfer.

**Comment by javierav** [comment]
All done! And thank you very much for the initial effort by creating this gem. I will keep you as colaborator on this repo.

**Comment by tboerger** [comment]
Wish you all the best with this rubygem! Good to see it in careful hands :)
